print("Welcome to the show")
city = input("Which city did you grow up in?\n")
#print("Which city did you grow up?" + input(""))
pet = input("What is the name of your first pet?\n")
print("Your band name could be:" + city + " " + pet)